apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stellar-core.fullname" . }}
  labels:
    app: {{ template "stellar-core.name" . }}
    chart: {{ template "stellar-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if not .Values.existingNodeSeedSecret }}
  nodeSeed: {{ required "nodeSeed is required if existingNodeSeedSecret is not provided" .Values.nodeSeed | b64enc }}
{{- end }}
{{- with .Values.gcloudServiceAccountKey }}
  gcloudServiceAccountKey: {{ . | b64enc }}
{{- end }}
{{- if .Values.postgresql.postgresqlPassword }}
  DATABASE_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
{{- end }}
{{- if .Values.aws.aws_access_key_id }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.aws_access_key_id | b64enc }}
{{- end }}
{{- if .Values.aws.aws_secret_access_key }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.aws_secret_access_key | b64enc }}
{{- end }}
