apiVersion: v1
kind: Service
metadata:
  name: {{ template "stellar-core.fullname" . }}-peer
  annotations:
    external-dns.alpha.kubernetes.io/hostname:  p2p.{{ .Values.rootDomain }}
    route53: "true"
  labels:
    app: {{ template "stellar-core.name" . }}
    chart: {{ template "stellar-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  # type: {{ .Values.peerService.type }}
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.peerService.port }}
      targetPort: 11625
      protocol: TCP
      name: peer


  {{- with .Values.peerService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  selector:
    app: {{ template "stellar-core.name" . }}
    release: {{ .Release.Name }}
